### ISSUE TITLE
Settings for input borders too specific

### ISSUE THREAD

**Issue by bradparker** [lukebrooker/minimal.css#1]
The use of `*:not()` is getting me here I think.

https://github.com/lukebrooker/minimal.css/blob/master/minimal.css#L42-L49

**Comment by lukebrooker** [comment]
Yeah… that's a thing. Will work on this soon.

**Comment by bradparker** [comment]
I might have a poke around myself. See if you can keep clear of a giant input type whitelist.

**Comment by bradparker** [comment]
🙏
